#!/usr/bin/python3
import keyboard
import atexit
from gi.repository import GLib
import dbus, dbus.service
from dbus.mainloop.glib import DBusGMainLoop

OBJECT_PATH='/com/github/ma1thew/pttd'
INTERFACE_NAME='com.github.ma1thew.pttd'
BUS_NAME='com.github.ma1thew.pttd'

class PttdServiceObject(dbus.service.Object):

    def __init__(self, key_id):
        dbus.service.Object.__init__(self, dbus.service.BusName(BUS_NAME, bus=dbus.SystemBus()), OBJECT_PATH)
        keyboard.on_press_key(key_id, self.EmitKeyDown)
        keyboard.on_release_key(key_id, self.EmitKeyUp)

    @dbus.service.signal(INTERFACE_NAME)
    def KeyUp(self):
        pass

    @dbus.service.signal(INTERFACE_NAME)
    def KeyDown(self):
        pass

    def EmitKeyUp(self, keyEvent):
        self.KeyUp()

    def EmitKeyDown(self, keyEvent):
        self.KeyDown()

def cleanup():
    print("Exiting...")
    GLib.MainLoop().quit()

if __name__ == '__main__':
    DBusGMainLoop(set_as_default=True)
    dbus_service = PttdServiceObject('alt')
    atexit.register(cleanup)
    try:
        GLib.MainLoop().run()
    except:
        pass
